Compression
elli-lib/elli_prometheus pull request #16
Opened 2016-11-26 10:23 UTC by deadtrickster

Negotiate encoding, support gzip and deflate.
New metric - telemetry_scrape_encoded_size_bytes.

#15

2016-11-28 20:47 UTC, deadtrickster commented
ping

2016-11-30 23:40 UTC, deadtrickster commented
ping :-)

2016-12-01 00:53 UTC, yurrriq requested changes
Other than the silly whitespace comment. This looks fine to me.

2016-12-01 00:53 UTC, yurrriq commented on src/elli_prometheus.erl
> +                                    %% _ -> Labels
Could you drop this change?

2016-12-01 07:45 UTC, merged

2016-12-01 07:45 UTC, deadtrickster commented
yay!